package tests;
import java.util.*;
import com.lycanitesmobs.core.spawner.location.*;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
public class LycanitesTest {
    static World world() { World w = new World() {}; w.loadedChunks.add(World.key(0, 0)); return w; }
    static boolean allInChunk00(List<BlockPos> ps) { for (BlockPos p : ps) if ((p.getX() >> 4) != 0 || (p.getZ() >> 4) != 0) return false; return true; }
    static void one(String name, BlockSpawnLocation loc, int expectedPositions) {
        World w = world();
        List<BlockPos> r = loc.getSpawnPositions(w, null, new BlockPos(8, 64, 8));
        boolean ok = w.chunksGenerated.isEmpty() && allInChunk00(r) && (expectedPositions < 0 || r.size() == expectedPositions);
        System.out.println("[B13] " + name + ": " + (ok ? "PASS" : "FAIL") + " - chunks loaded/generated by the scan " + w.chunksGenerated + ", " + r.size() + " positions returned"
                + (expectedPositions >= 0 ? " (expected " + expectedPositions + ", all in the loaded chunk)" : ""));
    }
    public static void run() {
        one("BlockSpawnLocation sweep", new BlockSpawnLocation(), 16 * 16 * 3);
        one("MaterialSpawnLocation sweep", new MaterialSpawnLocation(), 16 * 16 * 3);
        one("RandomSpawnLocation", new RandomSpawnLocation(), -1);
    }
}
